---

- name: "{{ ansible_distribution | lower }} | {{ ansible_distribution_release }} - Docker API is exposed"
  ansible.builtin.replace:
    path: /lib/systemd/system/docker.service
    regexp: '^(ExecStart.*)$'
    replace: '\1 -H=tcp://0.0.0.0:{{ docker_api_port }}'
  when: docker_api_expose
  notify: restart docker

- name: "{{ ansible_distribution | lower }} | {{ ansible_distribution_release }} - Docker API is not exposed"
  ansible.builtin.replace:
    path: /lib/systemd/system/docker.service
    regexp: '\s+-H=tcp://0.0.0.0:{{ docker_api_port }}'
    replace: ''
  when: not docker_api_expose
  notify: restart docker
